const PRODUCTS = [
  {
    id: 1,
    name: "Bluetooth & Wireless Over-Ear Headphones (Black",
    price: "Price: $12",
    image: "/assets/Images/bluetooth.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "electronics",
  },
  {
    id: 2,
    name: "Apple Vision Pro",
    price: "Price: $3400",
    image: "/assets/Images/visionpro.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "electronics",
  },
  {
    id: 3,
    name: "Running Shoe Red & White",
    price: "Price: $13.67",
    image: "/assets/Images/runningshoe.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "clothing",
  },
  {
    id: 4,
    name: "Apple iPhone Blue 64GB",
    price: "Price: $47.56",
    image: "/assets/Images/4.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "electronics",
  },
  {
    id: 5,
    name: "Bluetooth Over-Ear Headphones (White)",
    price: "Price: $53.06",
    image: "/assets/Images/5.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "electronics",
  },
  {
    id: 6,
    name: "Logitech Gamepad White for PC/PS3",
    price: "Price: $93.20",
    image: "/assets/Images/6.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "electronics",
  },
  {
    id: 7,
    name: "Premium Smart Watch (Black)",
    price: "Price: $25",
    image: "/assets/Images/7.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "electronics",
  },
  {
    id: 8,
    name: "Multicolor Modern Shoe for Her",
    price: "Price: $99.98",
    image: "/assets/Images/8.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "clothing",
  },
  {
    id: 9,
    name: "Apple iPhone (Brand New)",
    price: "Price: $87.22",
    image: "/assets/Images/9.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "electronics",
  },
  {
    id: 10,
    name: "Smart Watch with Latest Android OS",
    price: "Price: $11",
    image: "/assets/Images/10.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "electronics",
  },
  {
    id: 11,
    name: "Refrigrator",
    price: "Price: $99",
    image: "/assets/Images/refrigrator.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "homeappliance",
  },
  {
    id: 12,
    name: "Nikon Camera (Slightly Used) 750",
    price: "Price: $33",
    image: "/assets/Images/12.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "electronics",
  },
  {
    id: 13,
    name: "Red & Black Ganming Mouse for PC",
    price: "Price: $99",
    image: "/assets/Images/13.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "electronics",
  },
  {
    id: 14,
    name: "Multi Purpose College Bag Backpack",
    price: "Price: $44",
    image: "/assets/Images/14.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "homeappliance",
  },
  {
    id: 15,
    name: "White & Black Watch Concept",
    price: "Price: $22.22",
    image: "/assets/Images/15.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "electronics",
  },
  {
    id: 16,
    name: "Nike shoe",
    price: "Price: $84",
    image: "/assets/Images/shoe.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "clothing",
  },
  {
    id: 17,
    name: "Leather jacket",
    price: "Price: $45",
    image: "/assets/Images/leather_jacket.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "clothing",
  },
  {
    id: 18,
    name: "Microwave oven",
    price: "Price: $200.22",
    image: "/assets/Images/microwave_oven.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "homeappliance",
  },
  {
    id: 19,
    name: "Red jacket",
    price: "Price: $45",
    image: "/assets/Images/Red_jacket.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "clothing",
  },
  {
    id: 20,
    name: "Starshine Washing Machine",
    price: "Price: $200.22",
    image: "/assets/Images/Starshine_Washing.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "homeappliance",
  },
  {
    id: 21,
    name: "iPhone 15 Pro Max (Brand New)",
    price: "Price: $87.22",
    image: "/assets/Images/iphone15.jpg",
    details: "Quos, non, esse eligendi ab accusantium voluptatem. Accusamus .",
    category: "electronics",
  },
];

export default PRODUCTS;
